/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-06-24 19:46:45
 */
package kxr1.smartcollege.smartcollege.common;

/**
 * smartcollege云smartcollege应用-通用常量类<br>
 * 代码中不能存在硬编码敏感信息，如账号、密码、http外链、ftp外链、邮箱等。<br>
 * 标识或缓存的常量，需以"KEY_"、"FID_"、"ENTRY_"或"SUBENTRY_"作为变量的前缀。<br>
 *
 * @author kxr1
 * @date 2024-06-24 19:46:45
 */
public class AppflgConstant {
	
	public static final String KEY_APP_NAME = "smartcollege-smartcollege";

}
